name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build and push Docker image
        run: |
          docker build -t your-image-name .
          docker tag spotify:latest ${{ steps.ecr-login.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/spotify:latest
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ secrets.AWS_ACCOUNT_ID }}/spotify:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ap-south-1
          AWS_ACCOUNT_ID: your-account-id
